spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: admin-server
    boot:
        admin:
            url: http://localhost:${server.port}
eureka:
    client:
        registerWithEureka: true
        leaseRenewalIntervalInSeconds: 5
        serviceUrl:
            defaultZone:  http://eureka1:8761/eureka/