oauth2-server: http://localhost:8080
api-server: http://localhost:9080
server:
    port: 7080
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: onetwo-oauth2-resource
    boot:
        admin:
            url: http://localhost:9999
            context-path: /monitorui
security:
    oauth2:
        sso:
            # loginPath: /article**
        client:
            client-id: acme
            client-secret: acmesecret
            access-token-uri: ${oauth2-server}/oauth/token
            user-authorization-uri: ${oauth2-server}/oauth/authorize
        resource:
            # user-info-uri: http://localhost:8080/me
            # prefer-token-info: true
            token-info-uri: ${oauth2-server}/oauth/check_token
