server:
    port: ${PORT:8761}
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 10
        leaseExpirationDurationInSeconds: 30
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone:  http://localhost:8761/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        #enableSelfPreservation: false
            