server:
    port: ${PORT:8761}
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 3
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone:  http://localhost:8761/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
        evictionIntervalTimerInMs: 4000
            