server:
    port: 8080
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: onetwo-oauth2-authorization
security:
    oauth2:
        client:
            client-id: acme
            client-secret: acmesecret
            scope: read,write
            # auto-approve-scopes: '.*'
        authorization:
            checkTokenAccess: isAuthenticated()