spring:
    profiles:
        active: @{env}
    freemarker:
        suffix: .html
jfish: 
    profile: true
    mvc: 
        mediaTypes:
            json: application/json
            xls: application/vnd.ms-excel
            xml: application/xml
siteConfig:
    name: 后台管理系统