server:
    port: 20080
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 3
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone:  http://eureka1:8761/eureka/